### ISSUE TITLE
Pairing Bridge does not immediately show up.

### ISSUE THREAD

**Issue by kalanihelekunihi** [elgatosf/streamdeck-philipshue#1]
After successfully pairing a new bridge, it will not immediately be displayed in the Bridge drop down menu. It will instead remain unchanged from before with an option to add bridge.

After quitting and re-launching the Stream Deck manager application, the plugin will show the bridge as expected.

**Comment by Timac** [comment]
The issue might be fixed in Stream Deck 4.2 and in the Philips Hue plugin 1.1.1 that you can install from the Stream Deck store. Let me know if you still see this issue.

**Comment by themodio** [comment]
This issue still occurred for me today with all software up to date. Glad I saw this thread, because I thought it simply wasn't working. Restarting the Stream Deck software had it show up.
