### ISSUE TITLE
macos: color picker freezes the app 

### ISSUE THREAD

**Issue by estilen** [elgatosf/streamdeck-philipshue#11]
MacOS version: 10.14.5
Stream deck software version: 4.9.3 (13222)
Firmware version: 1.02.005
Hue plugin version: 1.3 - 02/02/2021

<img width="952" alt="Screenshot 2021-03-22 at 12 42 22" src="https://user-images.githubusercontent.com/23063174/111991474-4812eb80-8b0c-11eb-8fe7-9ebe7f29907c.png">

Trying to open up the color picker freezes the config app, have to close it before being able to use it again.

**Comment by tiptronic** [comment]
Not here... same setup.
Please make sure the color-picker doesn't show at an uncommon location, where it is hard to spot (for me it sometimes shows on my second monitor).

**Comment by estilen** [comment]
The very back corner of the 2nd monitor. Sorry to bother ye. 😂

**Comment by tiptronic** [comment]
Don't worry - happened to me too (as you might have guessed already ;)
