### ISSUE TITLE
Suggestion: Improved Brightness Controls

### ISSUE THREAD

**Issue by phyber** [elgatosf/streamdeck-philipshue#14]
Currently, we have an action that allows us to set the brightness to a specific, pre-defined level.

It would be nice improvement if we could have brightness up/down controls, perhaps with configuration to control how much each push of the button increases or decreases the brightness. eg. Each push of "Brightness Up" increases the brightness of Light 1 by 5%.  It would be good if the button was able to optionally display the brightness level too.

Thanks for considering this feature.

**Comment by elgatosystems** [comment]
Thanks for the suggestion. That's a good idea.

**Comment by akortesmaa** [comment]
Anyone working on this?

I've had the same idea ever since I bought my deck & it's been one of the biggest shortcomings of the plugin for me.
As Hacktoberfest is just around the corner, I could give this one a shot.

**Comment by richsark2000** [comment]
Please.  Mines still doesn’t not work reliably 


Thank you,

Richard
