### ISSUE TITLE
Cannot discover Hue bridge

### ISSUE THREAD

**Issue by DrHughHarvey** [elgatosf/streamdeck-philipshue#18]
Elgato Stream Deck mini + Stream Deck v5.1.1

Installed Streamdeck-Philips Hue SDK from this git.
Attempted to create button in Stream Deck to control Philips Hue -> Select Bridge -> Add new -> Discover bridges = No bridges found.

My bridge is on and connected to my network (same network as my mac), and synced to my iOS app and to Hue Sync, so everything works on that side. Out-of-home-control is enabled. No VPN in use.

I see many other people have had this issue, but no actual solution has been found other than to keep uninstalling/reinstalling/restarting which obviously is not working for me. 

Could the developers @dkern maybe address this issue?

**Comment by dkern** [comment]
This plugin gathers Information about your bridges by using the broker service under https://discovery.meethue.com
If you open this url in your network you should find all hue bidges. So a first check would be if you can open this url and see any response there.

You finde some information about it here: https://developers.meethue.com/develop/get-started-2/
And here is the code where it will be used: https://github.com/elgatosf/streamdeck-philipshue/blob/master/Sources/com.elgato.philips-hue.sdPlugin/plugin/js/philips/meethue.js#L210

**Comment by DrHughHarvey** [comment]
Just a thought - can I direct the SDK to look directly at the IP of my bridge (192.168.1.30) on my network? Do you think swapping out `var url = 'https://discovery.meethue.com';` with `var url = '192.168.1.30';` would work?

**Comment by dkern** [comment]
No, that would not work, because the function uses the response of this service to locate the bridge. Changing the url will just break everything. ;)

But a bit below that part you see what the lib does, it add the ip address and the bride id to an array and pass it to the callback. So you probably could replace the whole function and just respond your bridge.

Its hacky and completely untested, but this could work. ;)

```js
Bridge.discover = function(callback) {
    callback(true, [
        new Bridge('192.168.2.3', 'bridge_id')
    ]);
};
```

**Comment by dkern** [comment]
Ok, out of curiosity i gave it a short try. 😁 

![image](https://user-images.githubusercontent.com/917005/137360454-895e77f2-508d-4b58-8e14-0acb4449289c.png)

![image](https://user-images.githubusercontent.com/917005/137360406-1ff65aac-5162-4514-a07c-306437f797a7.png)

**Comment by DrHughHarvey** [comment]
That's awesome! Thanks

**Comment by junglejuz** [comment]
how do i download a release with this feature?

**Comment by tiptronic** [comment]
https://github.com/elgatosf/streamdeck-philipshue/blob/master/Release/com.elgato.philips-hue.streamDeckPlugin

**Comment by lee7670** [comment]
Hi, I am having the same issue. I downloaded and installed the 1.5 release, which seems to have this feature implemented, but when I add my bridge using it's IP, it says it pairs successfully and then does not show up in the bridges list.

![image](https://user-images.githubusercontent.com/3894242/147864361-ad143fa9-7c9b-44eb-b7bd-aa676a394376.png)

![image](https://user-images.githubusercontent.com/3894242/147864367-1925a98e-fb17-4a4f-91c1-913aae22f4b0.png)

**Comment by dannybloomfield** [comment]
Thanks @tiptronic - I found the bridge via IP, validated it correctly. BUT - it doesn't populate the bridge in the dropdown in the Stream Deck config UI.

**Comment by dkern** [comment]
I've added a test bridge to my network and can recreate that issue here. I try to find the reason for this, but I think this belongs also to the auto-discovery function of the meethue class. But we'll see ...

**Comment by dkern** [comment]
@dannybloomfield 
I fixed the issue and created a PR. If you want, you could test it: https://github.com/elgatosf/streamdeck-philipshue/pull/22

**Comment by logabog** [comment]
I am having the same issue as @dannybloomfield where after I add the bridge manually, it does not show up in the list.

**Comment by dkern** [comment]
> I am having the same issue as @dannybloomfield where after I add the bridge manually, it does not show up in the list.

Have you installed the version from github manually, or do you use the one you can install via SteamDeck software? So new version is not yet published, so you need to do it manually. Then the issue should be fixed.

**Comment by logabog** [comment]
> > I am having the same issue as @dannybloomfield where after I add the bridge manually, it does not show up in the list.
> 
> Have you installed the version from github manually, or do you use the one you can install via SteamDeck software? So new version is not yet published, so you need to do it manually. Then the issue should be fixed.

Yes - I uninstalled the original plugin from the SteamDeck application and then downloaded the version from github and installed that to Streamdeck. 

I was then presented with option to enter the Hue Bridge IP manually, and the bridge was found successfully. However. when I go to select the bridge in the app for the streamdeck Hue buttons, the bridge does not appear in the list.

**Comment by dannybloomfield** [comment]
Same

**Comment by dkern** [comment]
> Yes - I uninstalled the original plugin from the SteamDeck application and then downloaded the version from github and installed that to Streamdeck.

I have to ask again, because my question was a bit unclear. ;) Do you have installed the [source ](https://github.com/elgatosf/streamdeck-philipshue/tree/master/Sources/com.elgato.philips-hue.sdPlugin) manually from GitHub, or did you used the one in the [release](https://github.com/elgatosf/streamdeck-philipshue/tree/master/Release) folder? Because the release version will not work too. You really need to copy the source files manually.

**Comment by logabog** [comment]
I did not do that. Would I just download the master code from Github and copy it over the installed directory of the plugin? Where is the plugin installed by default on MacOS?
________________________________

**Comment by dkern** [comment]
I don't know where it is on mac. On windows its in the user app data folder. I would assume it is somewhere in the home folder on mac too. `C:\Users\%USERNAME%\AppData\Roaming\Elgato\StreamDeck\Plugins\com.elgato.philips-hue.sdPlugin` or `%USERPROFILE%\AppData\Roaming\Elgato\StreamDeck\Plugins\com.elgato.philips-hue.sdPlugin`

Inside there, search for the folder `com.elgato.philips-hue.sdPlugin` and copy the folder for backup. Then just copy all files from the source folder inside that folder and restart Streamdeck software.

**Comment by tiptronic** [comment]
On the Mac it's here:

`~/Library/Application Support/com.elgato.StreamDeck/Plugins`
or
`/Users/<yourusername>/Library/Application Support/com.elgato.StreamDeck/Plugins`

**Comment by dkern** [comment]
> On the Mac it's here

I add a little instruction for manual installing to the readme ...

**Comment by yval14** [comment]
![Capture d’écran 2022-06-04 123545](https://user-images.githubusercontent.com/106867985/171995563-524bdef8-e05d-4c3e-ae9a-359a2779b9b8.png)
I kill the app properly and it worked
