### ISSUE TITLE
Bridge not found if using VPN

### ISSUE THREAD

**Issue by Kakifrucht** [elgatosf/streamdeck-philipshue#2]
When connected through a VPN, even with local network sharing enabled, the bridge is not found. This is because querying the meethue endpoint, as it's done [here](https://github.com/elgatosf/streamdeck-philipshue/blob/master/Sources/com.elgato.philips-hue.sdPlugin/plugin/js/philips/meethue.js#L196), will not yield any results for the VPN's IP address. When turning off the VPN, allowing the discovery and then reconnecting the VPN it does work.

To fix this, I propose to cache the local network IP somewhere after pairing and using the Philips API call as a fallback strategy if the local network IP has changed.

**Comment by sli** [comment]
Not sure if you still need it, but I've implemented a rudimentary version of this that I'm going to refine over the next few days. Once it's done, maybe Elgato will accept a PR.

https://github.com/sli/streamdeck-philipshue

**Comment by mmurphyto** [comment]
@sli Your version would be a big help. For the app Huetro it also couldn't find my Bridge, but I was able to enter the manual IP. If this could be replicated for StreamDeck would make it much more useful.
