### ISSUE TITLE
Is a overall code cleanup wanted?

### ISSUE THREAD

**Issue by dkern** [elgatosf/streamdeck-philipshue#20]
Hello @elgatosystems 

In my last pull requests (https://github.com/elgatosf/streamdeck-philipshue/pull/7, https://github.com/elgatosf/streamdeck-philipshue/pull/19) I already added a lot of code quality improvement wherever I saw them. But I still didn't touched the _bigger_ issues. Like switching from `function() {}` to arrow functions, general update to newer JavaScript functions and techniques or remove all usage of `var`, like used for global variables and switch to a more robust approach.

But before I would do this, I would like to ask if you would want me to do this? I would like to update to a new and robust structure and improve anything on the way. 😉 

Please let me know what you think!

**Comment by dkern** [comment]
@tiptronic @elgatosystems 

Would some of you be so kind to close some tickets? That would help me to keep track. 😉 

These are already resolved:
- https://github.com/elgatosf/streamdeck-philipshue/issues/20 (resolved in pr #23)
- https://github.com/elgatosf/streamdeck-philipshue/issues/18 (resolved in #19)
- https://github.com/elgatosf/streamdeck-philipshue/issues/14 (resolved in #17 and #24)
- https://github.com/elgatosf/streamdeck-philipshue/issues/9 (this seem to be the same issue as i fixed in pr #22)
- https://github.com/elgatosf/streamdeck-philipshue/issues/8 (this seem to be the same issue as i fixed in pr #22)
- https://github.com/elgatosf/streamdeck-philipshue/issues/3 (resolved in #19 and #22)
- https://github.com/elgatosf/streamdeck-philipshue/issues/2 (this should be resolved with #22 too)

These are unsolvable:
- https://github.com/elgatosf/streamdeck-philipshue/issues/16 (not possible, commented)

And these are just old and could not verified:
- https://github.com/elgatosf/streamdeck-philipshue/issues/4 (no feedback)

Thank you!

**Comment by tiptronic** [comment]
Hey @dkern 
thanks for taking care of the issues and cleanup... 
I closed the ones you requested.

**Comment by dkern** [comment]
Hey @tiptronic 

Thanks very much, thats already better. ;) Would you like to close the other two too, i linked above? I already commented on them, so its clear why they could be closed (i think).

I will take a look to the remaining two issue by time.
