### ISSUE TITLE
Cannot Add Hue Bridge

### ISSUE THREAD

**Issue by lee7670** [elgatosf/streamdeck-philipshue#21]
I can force the steam deck to discover my bridge using either the manual IP entry from version 1.5 of the plugin, or manually alter the code in v1.4 to discover the bridge as indicated here (https://github.com/elgatosf/streamdeck-philipshue/issues/3). 

I cannot get it to save the bridge afterwards. It just shows add new and no bridges again.
![image](https://user-images.githubusercontent.com/3894242/147871242-7dc399b7-27cf-4314-8fad-1bf90923c298.png)

My hue lights work normally in my apartment. 

I am on Steam Deck Software 5.1.4.14753

**Comment by lee7670** [comment]
Apparently had to hard Reset before it would show up.

**Comment by SecretUnicorn** [comment]
> Apparently had to hard Reset before it would show up.

Can you specify what you mean with hard reset ?`I closed the stream deck application and it still does not show up
