### ISSUE TITLE
[request] temperature output from sensors

### ISSUE THREAD

**Issue by ikuria** [elgatosf/streamdeck-philipshue#27]
please add temperature output from sensors:

`{
	"state": {
		"temperature": 1701,
		"lastupdated": "2022-01-31T00:57:15"
	},
	"swupdate": {
		"state": "noupdates",
		"lastinstall": "2022-01-28T14:29:14"
	},
	"config": {
		"on": true,
		"battery": 100,
		"reachable": true,
		"alert": "none",
		"ledindication": false,
		"usertest": false,
		"pending": []
	},
	"name": "Hue temperature sensor 2",...`

**Comment by tiptronic** [comment]
hi @ikuria 
sorry for the late reply...
please try version 1.6.2
and don't forget to add to the discussion, if something is missing
