### ISSUE TITLE
Control "Light sync"

### ISSUE THREAD

**Issue by janvernieuwe** [elgatosf/streamdeck-philipshue#28]
I don't know if this is possible, but I'm looking to also enable or stop "light sync". 
My guess is that this needs to be done from the hue pc app alone and can't be done from the SDK?

If not, it would be a nice addition!

**Comment by dkern** [comment]
Sync uses a life stream of color from the pc, witch is done in the app. And afaik there is currently no way to access this from the outside. So I think not possible now.
