### ISSUE TITLE
Color Loop for Scene Switching

### ISSUE THREAD

**Issue by bauersimon** [elgatosf/streamdeck-philipshue#34]
The Hue App (and API) support enabling a "color loop" effect when fading to a new scene. This "will cycle through all hues using the current brightness and saturation settings". Would be nice to have a simple checkbox in the property inspector for this.

This is then communicated by adding `effect="colorloop"` to `/api/<username>/groups/<id>/action` (see the [docs](https://developers.meethue.com/develop/hue-api/groupds-api/#set-gr-state)).

**Comment by tiptronic** [comment]
@bauersimon please feel free to send a pull-request with those changes (or some more info). Afaik this sample doesn't support `color loop`. Is this a Hue API v2 or v3 feature? If it's the latter, we're out of luck (at least for now).
