### ISSUE TITLE
Stream Deck "not responding" with Hue plugin.

### ISSUE THREAD

**Issue by webshaun** [elgatosf/streamdeck-philipshue#37]
At this point I've tried all diagnostic steps.  The issue started when I pressed a button and got a yellow triangle.  Noticed that the bridge was no longer attached so I hit add bridge.  Got a message that it couldn't scan for the bridge.  Uninstalled the plugin, reinstalled it.  Afterwards Stream Deck has to be forcibly closed and the plugin has to be manually removed from appdata to open the software again.

I'm a fairly new Stream Deck user.  I've only had this unit for about a month.  This is the first time I'm seeing any issues, but I've been unable to resolve it.

I removed the connection from Stream Deck through the Philips Hue bridge.  No effect.  Reinstalled Stream Deck entirely with no effect.  Let me know what I should try next or if anyone else is having a similar issue.

**Comment by webshaun** [comment]
I seem to have found the solution.  The Stream Deck app was not loading on my primary monitor.  I've never seen an app with this behavior.  Interesting.

**Comment by tiptronic** [comment]
@webshaun If you think this is a StreamDeck application bug, please file a bug at Elgato's website. 
https://help.elgato.com/
