### ISSUE TITLE
Rotary knobs on the StreamDeck+ should control the brightness of a room/group

### ISSUE THREAD

**Issue by jeroenniesen** [elgatosf/streamdeck-philipshue#40]
As a Philips Hue and StreamDeck+ user, I want the rotary knobs on the StreamDeck+ to control the brightness of a room/group in Philips Hue so I can easily change the brightness of the lights in the room where I'm using my stream deck in.

## Current situation
Hue does not work with rotary knobs of the StreamDeck+

## Desired situation
Changing the brightness with the rotary knobs of the StreamDeck+ is possible

**Comment by tiptronic** [comment]
please try version 1.6.2
and don't forget to add to the discussion, if it works as expected

**Comment by jeroenniesen** [comment]
Just updated stream deck: it works as expected. Only when rotating the rotary buttons fast, the behaviour is somewhat strange. By quickly rotating I adjust the value quickly from (let say 40 to 70). After half a second, the value gets rewritten to 55. I guess this has to do with some throttling?

**Comment by tiptronic** [comment]
@jeroenniesen yes - that's likely a symptom of throttling... Unfortunately it also takes a bit until the light reports its current value... I think we can improve this behaviour over time. Meanwhile I recommend not rotating the dials too fast :)
