### ISSUE TITLE
Connection with Hue bridge gets lost 

### ISSUE THREAD

**Issue by niestadt** [elgatosf/streamdeck-philipshue#47]
Hello, 
One day after I installed the plugin on my Elgato Stream Deck Mini, the connection to the bridge seems lost. 
The keys don't control the Philips Hue anymore. 

Any idea how this might have happened?
What can I do to reconnect with Hue?

Regards, Dirk

**Comment by tiptronic** [comment]
Hi Dirk,
the Philips Hue bridge has some unfortunate limitations when it comes to auto-detection of the light. At some point it simply refuses to answer to connection-requests...

There are 2 ways to re-connect:
- remove all Hue keys from your StreamDeck and try again 10 Minutes later (or so).
- add the IP-address of the bridge in the PI's address-field.

Solving this is on our list already...

**Comment by niestadt** [comment]
Thank you for your response!

With kind regards,
Dirk Niestadt
