### ISSUE TITLE
Home Assistant's Emulated Hue cannot be connected 

### ISSUE THREAD

**Issue by SBRK** [elgatosf/streamdeck-philipshue#48]
I have stuff I would like to control from the Stream Deck + on my Home Assistant installation. I already have Emulated Hue setup on Home Assistant, but it's not detected automatically by the plugin, nor can I add it manually with the IP adress.

**Comment by tiptronic** [comment]
I'm closing this issue, because it seems out of scope for the plugin atm. 
If you still are interested in support of an 'Emulated Hue' (unfortunately I don't know what this is), we need more info on that.
