### ISSUE TITLE
not an issue but a hightly wanted suggestion

### ISSUE THREAD

**Issue by penguinpatrol** [elgatosf/streamdeck-philipshue#49]
there should absolutely be two buttons that can increase and decrease a set light brightness in increments for example - increasing a set light brightness by 5% (or 10% or however it is set) every time the button is pressed same for decreasing brightness - i dont think I'm going to be manually adding a button for every brightness anytime soon and i know many people such as myself want this kind of option!

**Comment by penguinpatrol** [comment]
silly me i have just discovered this feature although i have found if i spam the light brightness up by 10% then it takes a long time for it to register every button press until it allows for any other adjustment to be made (like brightness down) for example if i spam brightness up it will go up but if i keep spamming it the longer i press the button the longer it will take for any other button like brightness down or light off to be registered i dont know if its possible to fix this or not but its just something I've noticed

**Comment by tiptronic** [comment]
Hi @penguinpatrol 
sorry, but I don't know what you mean by `spamming` a button... and what you mean by `registered`. 

All actions should be instant - if you use a StreamDeck+ (the one with dials), you can increase/decrease by turning the dial and the light should follow immediately. If you press a key, the action should be executed instantly as well...

If that's not the case, it is likely that there's a problem on your network (or a firewall or proxy in between - that's hard to say)

**Comment by penguinpatrol** [comment]
by spamming a button i mean pressing it repeatedly very fastr if i want to turn the light up quickly from a brightness of lets say 10 i will be pressing the brightness up button a few times very fast which can take 1-3 seconds to register then -clicking it, wait for the brightness to change, click, wait, click, wait -  it may be a connection issue but both my pc and hue are connected directly into the same router unless there should be some software options i could change but i dont know

**Comment by tiptronic** [comment]
Most of the time these issues are related to the network... You should be able to tap the key pretty fast and the light should change pretty quick. Please keep in mind that the HUE bridge is connected via http, that means, if there is lots of traffic on your network, this can slow-down communication to the bridge.

Another (potential) issue might be that the overall time of your light-transitions is set to a long value (default is 400ms, iirc), which is the minimum time it takes until the value is fully changed. (I don't know where you can inspect/modify this value, but likely somewhere in the HUE app).

If you find the root of the problem, please let us know...
