### ISSUE TITLE
no access to smart scenes

### ISSUE THREAD

**Issue by nemroff** [elgatosf/streamdeck-philipshue#52]
Currently, this plugin does not support smart scenes (like the "Natural light" scene that Hue now offers).  It would be really great if this supported that!  In general, smart and dynamic scene control is lacking in this plugin.

The current workaround is probably using something like HomeAssistant as an intermediary.

From my initial research, I think this may be a large lift requiring some rearchitecting of the plugin.  The issues, ranked by my impression of easy to hard:

- Hue's API has a separate endpoint for `smart_scene` than `scene`.
  - When HomeAssistant's Hue plugin was updated to gain support for this, the PR implementing support called out "From a user perspective this is a bugfix while technically it's a new feature."
- It's only supported on Hue API v2, but this plugin is built with API v1.  There are plenty of breaking changes (most of which are covered in their [migration guide](https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/))… changing the code around for v2 requires some work, but it's doable.  However:
- Unlike API v1, v2 requires all commands to go over HTTPS, [with a caveat (per the Hue docs)](https://developers.meethue.com/develop/application-design-guidance/using-https/):
  - "The client has to validate the Hue Bridge certificate against the **Signify private CA Certificate for Hue Bridges**".
  - The client is also expected to "check the common name on the certificate matches the bridge id of the bridge you are trying to connect to".

I'm not sure what environment the Stream Deck's Javascript engine is running in, but I did not see any existing way to define custom trusted certificates in a plugin.  Given that limitation, I'd guess the best options are:

- During plugin setup, the user is instructed to install the Hue Bridge Root CA certificate system-wide as a trusted cert (definitely not ideal)
- The plugin uses an intermediary executable for communicating with the Hue Bridge which is able to define the cert as trusted (in my mind this is pretty much a proxy)
- The whole plugin is rewritten to handle all of the communication and plugin logic outside of the Stream Deck javascript environment and communicate back to the stream deck (maybe directly over the WebSocket connection, or via an intermediary skeleton plugin?)
- Do nothing.  Hope that Signify never follows through with its announced intent to [end access to the API over HTTP](https://developers.meethue.com/develop/application-design-guidance/using-https/) and [remove APIv1](https://developers.meethue.com/develop/hue-api-v2/), which would kill this plugin in its' present iteration.

**Comment by nemroff** [comment]
To be clear, I'm not just looking for someone to solve this for me, and I can contribute to this effort.  Beyond making sure this issue was raised, my intention was also to learn:

- Is there already a new version in the works?
- Is there any way to specify a trusted certificate within the scope of Stream Deck's Javascript engine?
- Alternatively, (though less ideal) is there a way to set the Stream Deck's JS engine to not verify / validate HTTPS communication for this one plugin?

If the answer is no to all three, that points to one of the more complicated (or otherwise less desirable) solutions.

**Comment by tiptronic** [comment]
Hi @nemroff 
thanks for your suggestions. 

We are aware that the current Hue-plugin is not capable of supporting all that new stuff and we are looking into it.

Currently it is not possible to simply switch from the currrent plugin to the new v2-API and https.
That's why certificate-validation won't work. So that needs to get created from scratch. It's not complicated, but the new Hue-API is massive and time is limited ;) 

Atm. there are no libraries available to help speeding up this process, so this will certainly take its time.

**Comment by tiptronic** [comment]
hey @nemroff - you're still in the loop?

**Comment by nemroff** [comment]
@tiptronic Yep, still here!

**Comment by tiptronic** [comment]
How do you use smart-scenes and how can I make them appear on the v2 endpoints?

**Comment by nemroff** [comment]
@tiptronic from the APIv2 endpoint it should be the same usage as with regular scenes. The only key difference is the resource url is /resource/smart_scene instead of /resource/scene

Here is the docs page with the relevant endpoints: https://developers.meethue.com/develop/hue-api-v2/api-reference/

**Comment by tiptronic** [comment]
That's not what I mean.... I mean, how you use smart scenes? (create them)? I have never seen anything in the `smart_scene` endpoint and was wondering what a `smart_scene` is..

**Comment by tiptronic** [comment]
@nemroff If you like you can give [this plugin](https://github.com/elgatosf/streamdeck-philipshue/discussions/61) an early spin
