### ISSUE TITLE
No ability to only have "off" for lights

### ISSUE THREAD

**Issue by Urbanpixels** [elgatosf/streamdeck-philipshue#56]
I've been using the plugin for a while and i've run into an issue i can't seem to solve. 

I start a "scene" with the stream deck which works fine as you'd expect. But i've no way to turn off this scene afterwards from the stream deck. 

The only option i have is for On/Off for a whole room. 

It would be nice if you could create just an OFF button. So i can start the scene as i do now. But have a seperate button for OFF so i can turn off all lights in the room where the scene is. 

Having this on the same button would be even better, Scene ON > Press again to turn all lights off in that room.

**Comment by Urbanpixels** [comment]
No, any scene in the hue app

**Comment by tiptronic** [comment]
Hey @ThioJoe and @Urbanpixels 
eager to try something new? 
We have some news on the Philips Hue coming (not done yet), but if you want to try, just let me know...
I'm looking forward for some testers...

**Comment by ThioJoe** [comment]
> Hey @ThioJoe and @Urbanpixels eager to try something new? We have some news on the Philips Hue coming (not done yet), but if you want to try, just let me know... I'm looking forward for some testers...

Yea sure why not, let me know what to do

**Comment by tiptronic** [comment]
OK - I just created a new pinned discussion:

https://github.com/elgatosf/streamdeck-philipshue/discussions/61

You're welcome to check that out... You can install it together with the old version - just in case
