### ISSUE TITLE
Cannot add hue bridge

### ISSUE THREAD

**Issue by RobTech1** [elgatosf/streamdeck-philipshue#57]
When i try to connect my hue bridge it doesnt add it. I do all the steps and it  is sucessful but it doesent add the bridge.

**Comment by tiptronic** [comment]
@RobTech1 Mac? Win? OS? Version?
-> and it does work with other apps on your computer?

**Comment by RobTech1** [comment]
I have the latest version and use it on windows 11. What I have noticed it works with all apps except hue and nanoleaf.

**Comment by GeekyEggo** [comment]
Hi @RobTech1, to help the team best investigate any potential issues, please can you provide the specific version information for:
- **Hue plugin version** - In Stream, right click one of the Hue actions.
- **Stream Deck version** - In Stream Deck, go to Preferences > General.
- **Windows 11 OS Build number** - Right click "This PC", the "OS Build" number will be there.
- **Hue bridge software version** - In the Hue app, Settings > Bridge (`i` symbol) > Software.

**Comment by RobTech1** [comment]
Plugin version: 1.6.5
Stream deck version: 6.5.0 (19904)
Windows: OS Build 22631.3085
 Hue bridge: 1.62.1962097030

**Comment by andrewhchen** [comment]
I'm also having the same issue as well. It won't let me connect with the bridge if I enter the IP manually and won't detect it automatically as well.

Plugin version: 1.6.5
Stream deck version: 6.5.1 (19929)
Mac: 11.7.10
Hue bridge: 1.62.1962154010

**Comment by tiptronic** [comment]
@andrewhchen @RobTech1 it would be * very* interesting to get some information about your network (router, subnets, proxy, whatever...);
If you enter your IP manually, I don't see any reason why the plugin should not connect to you local network (except there's some firewall or security settings involved)

@andrewhchen does `Mac: 11.7.10` mean `Big Sur`? (MacOS 11.x)?

**Comment by andrewhchen** [comment]
@tiptronic Indeed it is Big Sur. I also don't have a firewall and not sure why it won't connect to the manual IP as well. The error I get is "Bridge is not reachable. Please check the IP address" though I am able to ping the bridge IP on terminal without any issues.

**Comment by RobTech1** [comment]
@tiptronic I bought a new Orbi Pro router a few days ago but I still have the problem so I dont think it is the router configuration. But maybe some firewall problem with my computer.

**Comment by tiptronic** [comment]
@andrewhchen great to hear you got it working... Did you just reboot the router or do something else? I'd really like to understand where this issue comes from... 
Any info appreciated!

**Comment by tiptronic** [comment]
@RobTech1 Can you try to switch  off Wifi6 for a moment and try again? (did you use Wifi6 before too)?

**Comment by andrewhchen** [comment]
@tiptronic Hi Andy, I have two routers, one is a traditional router and one is a 5G integrated router. I was using the latter and when I plugged my hub to the former it didn't have the issue anymore. Both didn't have any firewall settings though not sure if there are any security settings for the 5G router that interfered with the Hue hub.

**Comment by RobTech1** [comment]
@tiptronic Still doesn't work after turning off wifi6, I also tried connecting my computer and the hue bridge to the same mesh but no difference. I used wifi 5 before.

**Comment by GilleGill** [comment]
Hey there, I'm experiencing connection issues too. I think it's the newest version of the Hue Bridge that is messing this up. I have two bridges, one is an older version and connects perfectly. The bridge that is now struggling to connect both with manually inputting the IP and searching, was able to connect two weeks ago, but after being unplugged it updated and is now unable to connect.

Plugin version: 1.6.5
Stream deck version: 6.6.0 (20583)
Windows: OS Build 19045.4291
Hue bridge: 1.61.1961135030 ( connects )
Hue bridge: 1.63.1963171020 ( does not connect )

**Comment by tiptronic** [comment]
@GilleGill I have 2 bridges here - both 1.63.1963171020 and they connect just fine...
Are both bridges connected to the MeetHue-system? (I could imagine the second bridge is a local bridge only).
If you don't mind, you're also invited to join [Discussions](https://github.com/elgatosf/streamdeck-philipshue/discussions/61) and try a new `early access` version of the Hue-plugin, which shouldn't have these limitations.

You can find details and a download-link [here](https://github.com/elgatosf/streamdeck-philipshue/discussions/61)
