### ISSUE TITLE
"unable to install 'unknown' plugin

### ISSUE THREAD

**Issue by JerkyChew899** [elgatosf/streamdeck-philipshue#58]
When trying to install via the Elgato store, nothing happens. So I found this repo and downloaded com.elgato.philips-hue.streamDeckPlugin, but when I double-click it it says "unable to install 'unknown' plugin. Is there something else I need to do? I'm running Windows 11.

**Comment by ThioJoe** [comment]
Seems like if the plugin failed installation with two different methods, it might be something else causing it. Are you able to install any other plugins?

**Comment by tiptronic** [comment]
It might be if you used the one on the Marketplace before, you can't additionally install the GitHub-version

**Comment by tiptronic** [comment]
Closing the issues due to no more feedback... if you still experience this issue, feel free to re-open.
