### ISSUE TITLE
Brightness "bounces" and slow to respond when moving rotary knobs too fast

### ISSUE THREAD

**Issue by HDClown** [elgatosf/streamdeck-philipshue#63]
This was mentioned in  ([issue 40](https://github.com/elgatosf/streamdeck-philipshue/issues/40)) when brightness for room/group was added.  

If you turn the knob to fast the brightness percentage on the display will bounce back/forth between the numbers it's trying to set.  There can also be extensive delay between a quicker knob turn and the lights applying the settings.  This behavior is worse if you do it with a room or group, but it's not quite as bad for an individual light.

I observe the following differences in behavior with the Hue mobile app:
- When you make a very quick change (ie. 25 to 100 in one quick sweep), there is about 0.5-1 second delay until the lights process the change
- When you make a slower (ie. slow slide from 0 to 50), the light brightness changes in near real-time.

I'm just spit balling here, but this seems like the mobile app may be sending a large/quick change as single command (hue lights, now change from current brightness to 100 brightness) and the slower changes are sent as individual commands (hue lights, now change from current brightness to 30, now change from current brightness to 35, now change from current brightness to 40, etc).  

Could this type of behavior be replicated in the knobs?  If you are slowly turning the knobs it sends every tick, but if you spin the knobs "fast", the command to change to the new brightness isn't sent until it has been observed that the knob hasn't spun for 0.5-1 second?

**Comment by tiptronic** [comment]
Hi @HDClown 
the differences you see are likely related to the fact that the plugin communicates with the bridge over HTTP, which is nowhere near realtime.
But you're invited to try out our current early access beta version, where we try to address all these issues.
That one is still not realtime, but should be much better than this version...
You can safely install this version alongside the old plugin and see if the changes work for you and join the discussion if you like.

https://github.com/elgatosf/streamdeck-philipshue/discussions/61

**Comment by HDClown** [comment]
Thanks for the heads up on the beta.   I will jump over to that discussion with my feedback on behavior.
