### ISSUE TITLE
Randomly cannot find hue bridge

### ISSUE THREAD

**Issue by boydfields** [elgatosf/streamdeck-philipshue#9]
NO HUE BRIDGE FOUND / DETECTED - REQUIRES RE-PAIRING EVERY-TIME

This has been happening now for several months but it has gotten worse in the coming weeks.

When the hue bridge is found all works wonderfully but randomly at other times it will not.  It means all my function keys do not work when controlling the lights.  

I am having to re-pair the Philips hue bridge on an almost everyday basis now by going to 'Add new bridge'.  The sequence is made even more difficult as the bridge is downstairs and I have to get to it, within 30 seconds, and press the button.

Please PLEASE can the owners/developers take a look into these issues.  Many people are having them.  The discovery protocol must be at fault.  At least make an option so we can set Static IP addresses.  I really only bought the Stream Deck so I could control the lights - seems pointless at present.

Please can somebody help resolve these issues.
Boyd

**Comment by leonpano2006** [comment]
i have same issue too

**Comment by ecker00** [comment]
Sharing this exact frustration for many months. Restarting the Stream Deck app sometimes works, so I made a PowerShell command to restart the stream deck.

`RestartStreamDeck.ps1`
```ps1
Stop-process -Name StreamDeck
Start-Sleep 1
& "C:\Program Files\Elgato\StreamDeck\StreamDeck.exe" --runinbk
```

Make a file with the above content and hook it up to a "System: Open" button with App / File as:
`powershell.exe "C:\path\to\RestartStreamDeck.ps1"`.

**Comment by jaeichel** [comment]
This might be related to https://github.com/elgatosf/streamdeck-philipshue/issues/8. I ran into networking issues specific to my VPN, but I've also seen this type of behavior too.

**Comment by BradleyAllanDavis** [comment]
> Sharing this exact frustration for many months. Restarting the Stream Deck app sometimes works, so I made a PowerShell command to restart the stream deck.
> 
> `RestartStreamDeck.ps1`
> 
> ```powershell
> Stop-process -Name StreamDeck
> Start-Sleep 1
> & "C:\Program Files\Elgato\StreamDeck\StreamDeck.exe" --runinbk
> ```
> 
> Make a file with the above content and hook it up to a "System: Open" button with App / File as: `powershell.exe "C:\path\to\RestartStreamDeck.ps1"`.

Force quitting the streamdeck app and relaunching seems to work for me on macOS, even with a VPN.
